### ISSUE TITLE
I am facing an error

### ISSUE THREAD

**Issue by shuklalove132** [ed-roh/chat-app#2]
Hi, i am a new react devloper so i am facing a small issue . I have copied your code word to word till 01:06:01 mins in your youtube video but when i type a message in it ,it doesn't get saved in the chat

the error i am getting is
```
             
       POST https://api.chatengine.io/chats/149632/messages/ 500
    at createError (createError.js:16:15)
    at settle (settle.js:17:12)
    at XMLHttpRequest.onloadend (xhr.js:66:7)
```
but in the video you are not facing this type of issue rn,
 so please help if you can.

Thanks!

**Comment by ElideZavala** [comment]
Still, I'm having the same error, it mainly arises when I add an image

**Comment by unfresh25** [comment]
Hey, did you solve this problem? I've been facing with it too.
